refactor gamma woutput cursorshape fractionalscale protocol imp
zccrs/waylib pull request #13
Opened 2024-06-20 15:13 UTC by lbwtw

2024-06-20 15:19 UTC, zccrs requested changes

2024-06-20 15:19 UTC, zccrs commented on examples/tinywl/CMakeLists.txt
> +    Qt6::QuickPrivate
为什么需要？

2024-06-20 15:19 UTC, zccrs commented on examples/tinywl/main.cpp
> +            });
对齐有问题？

2024-06-24 06:20 UTC, lbwtw commented on examples/tinywl/CMakeLists.txt
> +    Qt6::QuickPrivate
已删除

2024-06-24 06:33 UTC, zccrs requested changes

2024-06-24 06:33 UTC, zccrs commented on src/server/qtquick/woutputitem.cpp
> +    WOutputItemAttached *attached = static_cast<WOutputItemAttached *>(
直接叫 getOutputItem，传入的参数类型要  WOutput。另外不用创建一个 WOutputItemAttached 类型，直接用 qvariant_cast<WOutputItem*>(output->property(DATA_OF_WOUPTUT)) 获取。可以让 qmlAttachedProperties 调用这个新加的函数，而不是这个函数调用 qmlAttachedProperties。

2024-06-24 06:33 UTC, zccrs commented on src/server/protocols/woutputmanagerv1.h
> +    void updateConfig();
它是不是不需要公开，可以改为 private 的

2024-06-24 06:33 UTC, zccrs commented on src/server/protocols/woutputmanagerv1.h
> +struct WOutputState
加上 WAYLIB_SERVER_EXPORT

2024-06-24 06:33 UTC, zccrs commented on src/server/protocols/woutputmanagerv1.h
> +    WOutput *m_output;
试试是不是可以不以 "m_" 开头，作为public类还是要严谨些。

2024-06-24 07:20 UTC, lbwtw commented on src/server/qtquick/woutputitem.cpp
> +    WOutputItemAttached *attached = static_cast<WOutputItemAttached *>(
done

2024-06-24 07:20 UTC, lbwtw commented on src/server/protocols/woutputmanagerv1.h
> +    void updateConfig();
done

2024-06-24 07:20 UTC, lbwtw commented on src/server/protocols/woutputmanagerv1.h
> +struct WOutputState
done

2024-06-24 07:20 UTC, lbwtw commented on src/server/protocols/woutputmanagerv1.h
> +    WOutput *m_output;
done

2024-06-24 07:27 UTC, zccrs requested changes

2024-06-24 07:27 UTC, zccrs commented on src/server/qtquick/woutputitem.cpp
> +WOutputItem *WOutputItem::getOutputItem(WOutput *output)
在 qmlAttachedProperties 中调用 getOutputItem，尽量不要有重复性代码

2024-06-24 07:33 UTC, zccrs approved these changes

2024-06-24 07:33 UTC, merged